[package]
name = "vn_launcher"
version = "0.1.0"
edition = "2024"

[build-dependencies]
glib-build-tools = "0.22.0"

[dependencies]
dirs = "6.0.0"
gtk4 = {version = "0.11.0", features = ["v4_20"]}
rusqlite = "0.38.0"
